#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bspwm
Version  : 0.9.5
Release  : 1
URL      : https://github.com/baskerville/bspwm/archive/0.9.5.tar.gz
Source0  : https://github.com/baskerville/bspwm/archive/0.9.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: bspwm-license = %{version}-%{release}
BuildRequires : libxcb-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev

%description
## Description
*bspwm* is a tiling window manager that represents windows as the leaves of a full binary tree.

%package license
Summary: license components for the bspwm package.
Group: Default

%description license
license components for the bspwm package.


%prep
%setup -q -n bspwm-0.9.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541545820
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541545820
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bspwm
cp LICENSE %{buildroot}/usr/share/package-licenses/bspwm/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bspwm/LICENSE
